# Generated by Django 4.1.5 on 2023-03-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_url', models.URLField()),
                ('top_tag', models.CharField(max_length=255)),
                ('bottom_tag', models.CharField(max_length=255)),
                ('title_cut', models.CharField(max_length=255)),
                ('date_cut', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('nd_date', models.DateTimeField()),
                ('s_date', models.DateTimeField(auto_now_add=True)),
                ('not_date', models.DateField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.resource')),
            ],
        ),
    ]
